version: "3"
services:
    db:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            MSSQL_SA_USER: SA
            MSSQL_SA_PASSWORD: <your_sa_password>
            ACCEPT_EULA: Y
            DB_USER: <your_db_user>
            DB_PASSWORD: <your_db_password>
            DB_NAME: <your_db_name>
        expose:
            - "1433"
        ports:
            - "1433:1433"
